### PR TITLE
chore: remove matrix anywhere

### LINKED ISSUE #1706: Remove Matrix usage from the application
Remove Matrix usage from the application.

- [x] Remove Matrix login
- [x] Remove `MatrixContext` component
- [x] Remove `matrix-sdk` from package.json
- [x] Remove Matrix usage from submit model
- [x] Remove Matrix login from Settings screen
- [x] Check other places where Matrix is being used
- [x] Remove copying `olm.wasm` from webpack config

**Important**: The code should be removed but not commented.

### LINKED ISSUE #1778: Make Matrix id parameter optional when the user creates contact
Since Matrix is no more needed for multisig creation (please check [1756](https://github.com/novasamatech/nova-spektr/issues/1756)), Matrix id parameter in contacts may be optional.

### PR DESCRIPTION
**Pull request by Tbaut**
This is a remake of #1898
To be merged with https://github.com/novasamatech/nova-spektr/pull/1800 edit: done
closes #1706
closes https://github.com/novasamatech/nova-spektr/issues/1778

### CODE REVIEW

**Comment by pgolovkin** [comment]
@Tbaut looks good from functional point of view. 
1. Settings updated
2. Multisig creation flow update
3. Contacts page updated

I'm confused, that the data model is not changed
1. Please check the file https://github.com/novasamatech/nova-spektr/blob/72622b38ecc58aaff94799d74e75da0e0b52c5e1/src/renderer/shared/api/storage/service/dexie.ts#L46
2. matrixId has to be removed
3. Migration has to be added if needed https://github.com/novasamatech/nova-spektr/tree/e70993aa9e25e1baafc1e77255efc9669089c31c/src/renderer/shared/api/storage/migration

**Comment by pgolovkin** [comment]
@Tbaut please check if it's possible to remove Matrix databases.
image

**Comment by Tbaut** [comment]
regarding 1. we discussed a very similar case with Yaroslav a while ago, see here https://github.com/novasamatech/nova-spektr/pull/1729#discussion_r1578451491 so I've left it untouched. 

Regarding the DB (2 and 3), I don't think it's needed to update this file, to remove it or to do anything with it. It'll just be ignored in the future for anyone having it. I think removing it could damage things more than anything. What do you think?
We can discuss this in our call, see if I miss something.

**Review by Asmadek — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]

**Comment by Tbaut** [comment]
Sorry @Asmadek I mis-clicked and asked for review again, although I just wanted Sergey to check it.

**Review by johnthecat — APPROVED** [review]
Looks sexy to me

**Pull request merged**
