### PR TITLE
Feat: Wallet refactoring

### PR DESCRIPTION
**Pull request by tuul-wq**
- Wallet/accounts effector model
- Utility methods to check wallet/account type
- Updated wallet model according to [doc](https://app.diagrams.net/#G12BMyFvgL1o6ObRu5Ttqwyzp9M359rxm1%23%7B%22pageId%22%3A%22QVAxcpXtLhZr82ieB4b9%22%7D)
- Changed wallet management tab to the upcoming update (old implementation is not needed)
- Updated wallet/accounts usage across the app
- Wallet creation via `walletCreated` events
- Moved domain types to `shared/core`
- Added `id` property to `Account/Wallet/Contact`
- Created `storageService` that implements CRUD

To review:
- storageService
- wallet-model
- onboarding + walletModel.events
- types in shared/core

### CODE REVIEW

**Comment by tuul-wq** [comment]
Task linked: [CU-8692u7v5y Update how the application works with selected wallet](https://app.clickup.com/t/8692u7v5y)

**Comment by tuul-wq** [comment]
Task linked: [CU-8692vd6ym Transfer button does not appear if has WOW and PV the same wallet](https://app.clickup.com/t/8692vd6ym)

**Comment by tuul-wq** [comment]
Task linked: [CU-8692vnt7n Matrix log-in while multisig creation flow make "Create" button do nothing](https://app.clickup.com/t/8692vnt7n)

**Comment by tuul-wq** [comment]
Task linked: [CU-862kbb80v Research wallet data model for dynamic derivations](https://app.clickup.com/t/862kbb80v)

**Comment by tuul-wq** [comment]
Task linked: [CU-8692uq53a Refactor Storage service](https://app.clickup.com/t/8692uq53a)

**Review by egor0798 — APPROVED** [review]

**Pull request merged**
