### PR TITLE
fix: Remove description from confirmation modals

### LINKED ISSUE #1807: Remove multisig Description and Reject reason
Remove multisig description and reject reason.
1. Remove multisig Description on the create multisig operation screen
2. Remove filling Cancel reason when the user rejects multisig operation
3. Remove displaying multisig Description on multisig details screen
4. Remove displaying multisig Cancel reason on multisig details screen

Doc links: 
1. Create and display multisig operation doc https://docs.google.com/document/d/1wWnLwLnu4iddV9O1CJUkZ1ykY56oj18CKaMrI0TytUM/edit#heading=h.vcheoh7621sm
2. Operation confirmation screens doc https://docs.google.com/document/d/1oB7pX_tgBJJD4YI_pSjIwVmSHb7J1la-njYrNPYDmpc/edit#heading=h.vcheoh7621sm

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1807 

I thought these descriptions could be used for some other use-case than multisig, and since we removed the input, they would only be displayed when used, but it sounds like we want to remove them all no matter what, so here it is.

### CODE REVIEW

**Review by sokolova-an — COMMENTED** [review]
Should we, in this case, delete all description props from the confirm-modals and form-modals since we no longer use them?

**Comment by Tbaut** [comment]
Valid question, I am not sure this will never be used in the future, so I went with the safe way to only remove their display, but keep the stores.

**Review by tuul-wq — APPROVED** [review]

**Comment by pgolovkin** [comment]
@Tbaut I think it's better to remove code that is not used. And not going to be used in future.

**Comment by Tbaut** [comment]
ok I removed the descriptions form the stores @sokolova-an

**Review by johnthecat — APPROVED** [review]

**Pull request merged**
